# Generated by Django 4.1.7 on 2023-03-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_month_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='CONTEMPL',
            field=models.BooleanField(default=False),
        ),
    ]
