# Generated by Django 4.1.7 on 2023-03-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_todolist_contempl'),
    ]

    operations = [
        migrations.CreateModel(
            name='TODOList2020',
            fields=[
            ],
            options={
                'verbose_name': 'TODO 2020',
                'verbose_name_plural': 'TODOs 2020',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('todos.todolist',),
        ),
        migrations.AddField(
            model_name='todolist',
            name='eat1Hbeforego',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todolist',
            name='eatnoshit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todolist',
            name='facecare',
            field=models.BooleanField(default=False),
        ),
    ]
