# Generated by Django 4.1.7 on 2023-03-10 08:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0007_todolist2018_todolist_smalltalk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('date', models.DateField(default=datetime.date.today, primary_key=True, serialize=False)),
                ('dreams', models.TextField(blank=True, null=True)),
                ('events', models.TextField(blank=True, null=True)),
                ('ideas', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TODOList2016End',
            fields=[
            ],
            options={
                'verbose_name': 'TODO 2016[end]',
                'verbose_name_plural': 'TODOs 2016[end]',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('todos.todolist',),
        ),
        migrations.CreateModel(
            name='TODOList2017AugDec',
            fields=[
            ],
            options={
                'verbose_name': 'TODO 2017[2] Aug-Dec',
                'verbose_name_plural': 'TODOs 2017[2] Aug-Dec',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('todos.todolist',),
        ),
        migrations.CreateModel(
            name='TODOList2017JanJul',
            fields=[
            ],
            options={
                'verbose_name': 'TODO 2017[1] Jan-Jul',
                'verbose_name_plural': 'TODOs 2017[1] Jan-Jul',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('todos.todolist',),
        ),
        migrations.AddField(
            model_name='todolist',
            name='date',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='todos.day'),
        ),
    ]
