# Generated by Django 4.1.7 on 2023-03-10 09:08

from django.db import migrations, models
import django.db.models.deletion
import todos.models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0008_day_todolist2016end_todolist2017augdec_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolist',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='todolist2023',
            options={'ordering': ['-date'], 'verbose_name': 'TODO 2023', 'verbose_name_plural': 'TODOs 2023'},
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='daydate',
        ),
        migrations.AlterField(
            model_name='todolist',
            name='date',
            field=models.OneToOneField(default=todos.models.thisday, on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='todos.day'),
        ),
    ]
