# Generated by Django 4.1.7 on 2023-03-10 09:43

from django.db import migrations, models
import django.db.models.deletion
import todos.models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0009_alter_todolist_options_alter_todolist2023_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='todolist',
            options={'ordering': ['-date__date']},
        ),
        migrations.AlterModelOptions(
            name='todolist2023',
            options={'ordering': ['-date__date'], 'verbose_name': 'TODO 2023', 'verbose_name_plural': 'TODOs 2023'},
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='month',
        ),
        migrations.AddField(
            model_name='day',
            name='month',
            field=models.ForeignKey(default=todos.models.thismonth, on_delete=django.db.models.deletion.PROTECT, related_name='days', to='todos.month'),
        ),
    ]
