# Generated by Django 4.1.7 on 2023-03-10 10:41

from django.db import migrations, models
import django.db.models.deletion
import todos.models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0010_alter_day_options_alter_todolist_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='todolist',
            name='date',
            field=models.OneToOneField(default=todos.models.thisday, on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='todolist', serialize=False, to='todos.day'),
        ),
    ]
