# Generated by Django 4.1.7 on 2023-03-11 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0011_alter_day_options_alter_todolist_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='CONTEMPL',
        ),
    ]
