# Generated by Django 4.1.7 on 2023-03-25 09:33

from django.db import migrations, models
import django.db.models.deletion
import todos.models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0014_remove_todolist_dreams'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('yeardate', models.TextField(default=todos.models.yeardate, primary_key=True, serialize=False)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-yeardate'],
            },
        ),
        migrations.AddField(
            model_name='month',
            name='year',
            field=models.ForeignKey(default=todos.models.thisyear, on_delete=django.db.models.deletion.PROTECT, related_name='months', to='todos.year'),
        ),
    ]
